name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test:jest

      - name: Build
        run: npm run build

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          build: npm run build
          start: npm start
